import { useNavigate } from "react-router-dom";
import { FaChartBar, FaBell, FaFileAlt, FaDatabase } from "react-icons/fa";
import "./home.css";

function Home() {
  const navigate = useNavigate();

  return (
    <div className="home-container">

      {/* HERO SECTION */}
      <div className="hero">
        <h1>Compliance Monitoring Platform</h1>
        <p>
          Monitor court cases, track risks, and manage alerts — all in one place.
        </p>

        <div className="hero-buttons">
          <button onClick={() => navigate("/dashboard")}>
            Go to Dashboard
          </button>

          <button
            className="secondary"
            onClick={() => navigate("/alerts")}
          >
            View Alerts
          </button>
        </div>
      </div>

      {/* FEATURES */}
      <div className="features">

        <div className="feature-card" onClick={() => navigate("/dashboard")}>
          <FaChartBar />
          <h3>Dashboard</h3>
          <p>Visualize case data and insights in one place.</p>
        </div>

        <div className="feature-card" onClick={() => navigate("/alerts")}>
          <FaBell />
          <h3>Alerts</h3>
          <p>Track and manage alerts generated by the system.</p>
        </div>

        <div className="feature-card" onClick={() => navigate("/reports")}>
          <FaFileAlt />
          <h3>Reports</h3>
          <p>Download detailed reports for analysis.</p>
        </div>

        <div className="feature-card" onClick={() => navigate("/entities")}>
          <FaDatabase />
          <h3>Data Center</h3>
          <p>Manage and monitor all your entities.</p>
        </div>

      </div>

      {/* HOW IT WORKS */}
      <div className="steps-section">
        <h2>How it works</h2>

        <div className="steps">

          <div className="step">
            <span>1</span>
            <h4>Add Entities</h4>
            <p>Upload or manage vendors and clients in Data Center.</p>
          </div>

          <div className="step">
            <span>2</span>
            <h4>Monitor Cases</h4>
            <p>System scans and identifies legal cases automatically.</p>
          </div>

          <div className="step">
            <span>3</span>
            <h4>Get Alerts</h4>
            <p>Receive alerts for important case updates.</p>
          </div>

          <div className="step">
            <span>4</span>
            <h4>Download Reports</h4>
            <p>Analyze data through downloadable reports.</p>
          </div>

        </div>
      </div>

      {/* WHY SECTION */}
      <div className="why-section">
        <h2>Why use this platform?</h2>

        <div className="why-points">
          <div>✔ Centralized case monitoring</div>
          <div>✔ Automated alert system</div>
          <div>✔ Easy report generation</div>
          <div>✔ Scalable for multiple entities</div>
        </div>
      </div>

    </div>
  );
}

export default Home;
