import { useNavigate } from "react-router-dom";
import { FaChartBar, FaBell, FaFileAlt, FaDatabase } from "react-icons/fa";
import "./home.css";

function Home() {
  const navigate = useNavigate();

  return (
    <div className="home-container">

      {/* HERO SECTION */}
      <div className="hero">
        <h1>Legal Monitoring Platform</h1>
        <p>
          Monitor court cases, track risks, and manage alerts — all in one place.
        </p>

        <div className="hero-buttons">
          <button onClick={() => navigate("/dashboard")}>
            Go to Dashboard
          </button>

          <button className="secondary" onClick={() => navigate("/alerts")}>
            View Alerts
          </button>
        </div>
      </div>

      {/* FEATURES SECTION */}
      <div className="features">

        <div className="feature-card" onClick={() => navigate("/dashboard")}>
          <FaChartBar />
          <h3>Dashboard</h3>
          <p>Visualize case data and insights in one place.</p>
        </div>

        <div className="feature-card" onClick={() => navigate("/alerts")}>
          <FaBell />
          <h3>Alerts</h3>
          <p>Track and manage alerts generated by the system.</p>
        </div>

        <div className="feature-card" onClick={() => navigate("/reports")}>
          <FaFileAlt />
          <h3>Reports</h3>
          <p>Download detailed reports for analysis.</p>
        </div>

        <div className="feature-card" onClick={() => navigate("/entities")}>
          <FaDatabase />
          <h3>Data Center</h3>
          <p>Manage and monitor all your entities.</p>
        </div>

      </div>

      {/* INFO SECTION */}
      <div className="info-section">
        <h2>How it works</h2>
        <p>
          This platform continuously monitors legal cases related to your entities,
          identifies risks, and keeps you updated through alerts and reports.
        </p>
      </div>

    </div>
  );
}

export default Home;
